@HappyShoppingClone.API_HostAddress = http://localhost:5041

GET {{HappyShoppingClone.API_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{HappyShoppingClone.API_HostAddress}}/weatherforecast/
Accept: application/json

###
